[package]
name = "Nexaro-Explorer"
version = "0.1.0"
edition = "2024"

[dependencies]
i-slint-backend-winit = "1.17.1"
i-slint-renderer-skia = "1.17.1"
notify = "8"
slint = "1.17.1"
chrono = "0.4"
open = "5"
dirs = "6"
windows = { version = "0.48.0", features = ["Win32_Foundation", "Win32_Storage_FileSystem", "Win32_UI_Shell", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging"] }
[build-dependencies]
slint-build = "1"
